### ISSUE TITLE
Add options for disabilities

### ISSUE THREAD

**Issue by presssssure** [WalnutProgramming/room-finder#30]
Buildings should have alternative elevator routes that can be used instead of stairs and can be toggled on or off depending on if the user turns on a “disability mode.” This could be a third parameter on the .getDirections() function on a building. Ex: Hospital.getDirections(“A”, ”B”, true); to use instructions for disabilities.

Some buildings also have more elevators than stairwells, so they might just want to use elevators and not stairs. Lots of schools don’t want able-bodied students to use the elevators.

**Comment by Aurelius333** [comment]
Here’s how I imagine this working: when you define a node (staircase or fork), you can specify what type of node it is. 

```ts
  // ...
  new Elevator({
    /*options...*/,
    nodeType: “accessibility-only”
  }),
  //...
  new Ramp({
    /*options...*/
    nodeType: “accessible”
  }),
```

Then, when you’re getting directions, you can decide which connection types to allow for that set of directions:
```ts
// for people without accessibility needs
building.getDirections({
  from: “3104”,
  to: “3113”,
  nodeTypes: [“default”, “accessible”]
})

//OR

// for people with accessibility needs
building.getDirections({
  from: “3104”,
  to: “3113”,
  nodeTypes: [“accessibility-only”, “accessible”]
})
```

**Comment by Aurelius333** [comment]
* I'm thinking now that each builtin class can have its own default `connectionType`. For example, by default, a `Fork` will have `connectionType` "Fork", an `Elevator` will have `connectionType` "Elevator", etc. (You can still specify your own `connectionType`s.) By default, all nodeTypes will be included when you use `getDirections`.

* Also, instead of including an option for `allowedConnectionTypes`, I'm thinking about having a new method called `withAllowedConnectionTypes` that returns a new `Building`.
```ts
const Building = new Building(/* ... */);

// returns directions that can use any connectionType
building.getDirections("3104", "3113"); 

// returns directions that can use only these connectionTypes
building
  .withAllowedConnectionTypes(["Stairs", "Ramp", "Fork"])
  .getDirections("3104", "3113");

// returns directions that can use only these connectionTypes
building
  .withAllowedConnectionTypes(["Elevator", "Ramp", "Fork"])
  .getDirections("3104", "3113");
```

**Comment by presssssure** [comment]
That actually sounds really good! Then connection types don't have any inherent meaning which is good for usability for other buildings.
